# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: 0.1.$(Rev:r)

variables:
  - group: theale-prism-central

trigger:
  - master

pool: 'default'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build job
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        repository: ukdemo/calm-dsl
        command: build
        arguments: '--no-cache'
        tags: |
          latest
          $(Build.BuildId)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: ukdemo/calm-dsl
        command: push
        tags: |
          latest
          $(Build.BuildId)             

      
- stage: Deploy
  jobs:
  - deployment: DeployCalm
    displayName: 'Deploy to Calm'
    container:
      image: ukdemo/calm-dsl:latest
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          
          - script: |
              sudo ln -s /root/.local/bin/calm /usr/local/bin/calm
              sudo calm init dsl -i $(pc_ip) -P $(pc_port) -u $(pc_user) -p $(pc_pass) -pj $(calm_projectName)
              sudo calm run runbook -w -i jg-tf-aws_vpc
              sudo py3clean .
