# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: 0.1.$(Rev:r)

variables:
  - group: theale-prism-central

trigger:
  - webpage

pool: 'default'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: BuildWebpage
    displayName: Build job
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        Dockerfile: Dockerfile.webpage
        repository: ukdemo/webpage
        command: build
        # arguments: '--no-cache'
        tags: |
          latest
          $(Build.BuildId)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: ukdemo/webpage
        command: push
        tags: |
          latest
          $(Build.BuildId)
  - job: BuildDsl
    displayName: Build job
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        Dockerfile: Dockerfile.dsl
        repository: ukdemo/calm-dsl
        command: build
        # arguments: '--no-cache'
        tags: |
          latest
          $(Build.BuildId)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: ukdemo/calm-dsl
        command: push
        tags: |
          latest
          $(Build.BuildId)


- stage: Deploy
  jobs:
  - deployment: DeployWepage
    displayName: 'Deploy to Calm'
    container:
      image: ukdemo/calm-dsl:latest
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - script: |
              echo 'variable_list = [
              {"value": {"value": "ukdemo/webpage:$(Build.BuildId)"}, "name": "KUBERNETES_DEPLOYMENT_CONTAINER_IMAGE"},
              ]' > variables.py
              sudo ln -s /root/.local/bin/calm /usr/local/bin/calm
              sudo calm init dsl -i $(pc_ip) -P $(pc_port) -u $(pc_user) -p $(pc_pass) -pj $(calm_projectName)
              sudo calm run action -w -a jg-dsl104 -r variables.py UpdateApp
              sudo py3clean .
